#!/usr/bin/env bash
# Display information about subdomains.
# Usage: ./1-world_wide_web <domain> <subdomain>

# create a function to find the info
domainINFO () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  domainINFO "$1" "www"
  domainINFO "$1" "lb-01"
  domainINFO "$1" "web-01"
  domainINFO "$1" "web-02"
elif [ "$#" == 2 ]
then
  domainINFO "$1" "$2"
fi
