#!/usr/bin/env bash
# redirects
apt update -y
apt install nginx  -y
echo "Hello World!" > /var/www/html/index.html

sed -i "s/server_name _;/server_name _;\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.github.com\/imoleBytes;\n\t}\n/g" /etc/nginx/sites-available/default

sudo service nginx restart
