#!/usr/bin/env bash
# Install nginx on your web-01 and serve "hello World"
apt update -y
apt install nginx -y

ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html

configServer=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
    Redirect 301 /redirect_me https://wwww.youtube.com/;
}"

echo "$configServer" > /etc/nginx/sites-enabled/default

if [ "$(pgrep -c nginx)" -le 0 ]
then
	service nginx start
else
	service nginx restart
fi
