#!/usr/bin/env bash
# redirects
sudo apt update -y
sudo apt install nginx  -y
sudo echo "Hello World!" > /var/www/html/index.html


echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301 https://www.youtube.com/;
   }
   location / {
        try_files \$uri \$uri/ =404;
    }
}" > default
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
