#!/usr/bin/env bash
# Install nginx on your web-01 and serve "hello World"
sudo apt update -y
sudo apt install nginx -y

sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html

configServer=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
    Redirect 301 /redirect_me https://wwww.youtube.com/;
}"

echo -e "$configServer" > /etc/nginx/sites-enabled/default

if [ "$(pgrep -c nginx)" -le 0 ]
then
	service nginx start
else
	service nginx restart
fi
