#!/usr/bin/env bash

sed -i "s/server_name _;/server_name _;\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.github.com\/imoleBytes;\n\t}\n/g" default
# sed -i "s/server_name _;/server_name _;\n\tlocation/g" default
#     location /redirect_me {
#         return 301 https://www.github.com/imoleBytes;
#     }

#     location / {
#             try_files \$uri \$uri/ =404;
#         }
# }" > default
# sudo mv -f default /etc/nginx/sites-available/default
