#!/usr/bin/env bash
# Double the number of webservers
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
# Write 0-custom_http_response_header so that it configures a brand new Ubuntu machine to the requirements asked in this task
apt update -y
apt install nginx -y
echo "Hello World!" > /var/www/html/index.html
service nginx start
