#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server

src_path=$1
ip_addr=$2
username=$3
path_to_pkey=$4

if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -r  -i "$path_to_pkey" "$src_path" "$username@$ip_addr:~"
fi
