#!/usr/bin/env bash
# Install and configure HAproxy (Load balancer)
# To distribute traffics to 2 webservers
# Using roundrobin algorithm
apt update
apt upgrade
apt install -y haproxy
echo "ENABLED=1" >> /etc/default/haproxy
my_server_config=\
"
frontend haproxy-main
        bind *:80
        option forwardfor
        default_backend nginx_servers

backend nginx_servers
        balance roundrobin
        server web-01 100.26.158.41:80 check
        server web-02 54.236.41.243:80 check

"
echo "$my_server_config" >> /etc/haproxy/haproxy.cfg
