#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.bak
echo "127.0.0.2		localhost" > ~/hosts.bak
echo "8.8.8.8		facebook.com" >> ~/hosts.bak
cp -f ~/hosts.bak /etc/hosts
